export const chatConstants = {
  SET_USERS: 'chat/SET_USERS',
  SET_MESSAGES: 'chat/SET_MESSAGES',
  ADD_MESSAGE: 'chat/ADD_MESSAGE',
  REMOVE_LAST_MESSAGE: 'chat/REMOVE_LAST_MESSAGE',
  SET_MESSAGES_LOADING: 'chat/SET_MESSAGES_LOADING',
};
